= SELinux C-style Policy Language Reference Documentation

[NOTE]
=====
While CSP is largely inspired by and ultimately compiles down to CIL policy, an understanding of CIL should not be required to understand the language reference documentation.
=====

== Syntax

Identifiers:: An identifier is any valid ASCII string that begins with an alpha character or `\_`, and follows with any alphanumeric character or `_`.
An example regular expression matching this pattern wouuld be: `[a-zA-Z_][a-zA-Z0-9_]*`.

== Policy Structure

The fundamental building blocks of policy structure that differentiate CSP from the simple kernel policy language.

<<01-namespaces.adoc#,Namespaces>>::
Namespaces provide a structured approach to building blocks of reusable policy.

<<02-conditionals.adoc#,Conditionals>>::
Conditionals allow the policy author to disable/enable policies based on the value of runtime or build-time toggles.

<<03-macros.adoc#,Macros>>::
Function-like blocks of policy that can be parameterized and invoked.
